
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/gatsby-site
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Fallback cache to be used
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Gatsby Build
          command: npm run build
                 git config user.email "nilesh_s@techjoomla.com"
                git config user.name "nilesh5995"
      - run:
          name:  Deploy
          command: npm run deploy
      - add_ssh_keys:
          fingerprints:
            - "ac:9e:f4:81:08:44:1a:78:13:78:a1:61:81:00:42:5e"







